# Generated by Django 4.2.21 on 2025-05-15 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("flashcards", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sentence",
            options={
                "ordering": ["csv_number", "translation_direction"],
                "verbose_name": "Sentence Card",
                "verbose_name_plural": "Sentence Cards",
            },
        ),
        migrations.AddField(
            model_name="sentence",
            name="translation_direction",
            field=models.CharField(
                choices=[("S2E", "Spanish to English"), ("E2S", "English to Spanish")],
                default="S2E",
                help_text="Direction of translation for this card (e.g., Spanish to English)",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="sentence",
            name="csv_number",
            field=models.IntegerField(
                help_text="Original number from CSV for reference"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sentence",
            unique_together={("csv_number", "translation_direction")},
        ),
    ]
