# Generated by Django 4.2 on 2025-12-25 17:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_alter_sentence_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('card_id', models.AutoField(primary_key=True, serialize=False)),
                ('pair_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Shared ID for a forward+reverse pair')),
                ('front', models.TextField(help_text='Prompt (front of card)')),
                ('back', models.TextField(help_text='Answer (back of card)')),
                ('language', models.CharField(blank=True, default='', help_text="Optional language label (e.g., 'es', 'de')", max_length=32)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Optional list of tags')),
                ('notes', models.TextField(blank=True, default='', help_text='Optional notes')),
                ('source', models.TextField(blank=True, default='', help_text='Optional source')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of creation')),
                ('last_modified_date', models.DateTimeField(auto_now=True, help_text='Timestamp of last update to card or SRS data')),
                ('ease_factor', models.FloatField(default=2.5, help_text='For SM2-like algorithm')),
                ('interval_days', models.IntegerField(default=0, help_text='Current interval in days; 0 for new/learning cards')),
                ('next_review_date', models.DateField(default=django.utils.timezone.now, help_text='Date for next scheduled review')),
                ('is_learning', models.BooleanField(default=True, help_text='True if card is in learning phase, False if graduated/reviewing')),
                ('consecutive_correct_reviews', models.IntegerField(default=0, help_text='Number of consecutive reviews with score > 0.8')),
                ('total_reviews', models.IntegerField(default=0, help_text='Counter for how many times this card has been reviewed')),
                ('total_score_sum', models.FloatField(default=0.0, help_text='Sum of all scores for this card, to calculate average')),
                ('linked_card', models.OneToOneField(blank=True, help_text='The reverse card for this card (if any).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_card_reverse', to='flashcards.card')),
            ],
            options={
                'verbose_name': 'Card',
                'verbose_name_plural': 'Cards',
                'ordering': ['-next_review_date', 'card_id'],
            },
        ),
        migrations.CreateModel(
            name='CardReview',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Timestamp of the review')),
                ('user_score', models.FloatField(help_text='Score given by user, 0.0 to 1.0')),
                ('user_comment_addon', models.TextField(blank=True, help_text='Additional comment made by user during this specific review', null=True)),
                ('typed_input', models.TextField(blank=True, help_text='Optional typed input stored with the review (not graded yet)', null=True)),
                ('interval_at_review', models.IntegerField(help_text='The interval setting for the card before this review took place')),
                ('ease_factor_at_review', models.FloatField(help_text='The ease factor for the card before this review took place')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='flashcards.card')),
            ],
            options={
                'verbose_name': 'Card Review',
                'verbose_name_plural': 'Card Reviews',
                'ordering': ['-review_timestamp'],
            },
        ),
    ]
