# Generated by Django 4.2 on 2025-12-25 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0003_card_cardreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this card', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sentence',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User who owns this sentence card', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sentences', to=settings.AUTH_USER_MODEL),
        ),
    ]
