# Generated by Django 4.2 on 2026-01-02 21:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flashcards', '0006_cardreview_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('lesson_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('text', models.TextField(help_text='Full text content')),
                ('language', models.CharField(default='es', help_text='Language code (es, de, etc.)', max_length=10)),
                ('audio_url', models.URLField(blank=True, help_text='URL to audio file', null=True)),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='lessons/audio/')),
                ('source_type', models.CharField(choices=[('text', 'Text Paste'), ('youtube', 'YouTube'), ('url', 'URL'), ('file', 'File Upload')], default='text', max_length=50)),
                ('source_url', models.URLField(blank=True, help_text='Original source URL', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sentence_translations', models.JSONField(blank=True, default=dict, help_text='Cached translations: {sentence_text: translation}')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('token_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(help_text='Surface form of the token', max_length=200)),
                ('normalized', models.CharField(db_index=True, help_text='Normalized form (lowercase, punctuation stripped)', max_length=200)),
                ('start_offset', models.IntegerField(help_text='Character offset where token starts')),
                ('end_offset', models.IntegerField(help_text='Character offset where token ends')),
                ('translation', models.TextField(blank=True, help_text='Cached translation/gloss', null=True)),
                ('dictionary_entry', models.JSONField(blank=True, default=dict, help_text="Dictionary data: {meanings: [...], part_of_speech: '...'}")),
                ('clicked_count', models.IntegerField(default=0, help_text='How many times user clicked this token')),
                ('added_to_flashcards', models.BooleanField(default=False, help_text='Whether user added this to flashcards')),
                ('card_id', models.IntegerField(blank=True, help_text='ID of Card created from this token', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='flashcards.lesson')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'ordering': ['start_offset'],
            },
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('phrase_id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Full phrase text')),
                ('normalized', models.CharField(db_index=True, max_length=500)),
                ('translation', models.TextField(blank=True, null=True)),
                ('added_to_flashcards', models.BooleanField(default=False)),
                ('card_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phrases', to='flashcards.lesson')),
                ('token_end', models.ForeignKey(help_text='Last token in phrase', on_delete=django.db.models.deletion.CASCADE, related_name='phrase_ends', to='flashcards.token')),
                ('token_start', models.ForeignKey(help_text='First token in phrase', on_delete=django.db.models.deletion.CASCADE, related_name='phrase_starts', to='flashcards.token')),
            ],
            options={
                'verbose_name': 'Phrase',
                'verbose_name_plural': 'Phrases',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['lesson', 'start_offset'], name='flashcards__lesson__b30399_idx'),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['normalized'], name='flashcards__normali_47753f_idx'),
        ),
    ]
