# Generated by Django 4.2 on 2026-01-02 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0007_lesson_token_phrase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='last_listened_at',
            field=models.DateTimeField(blank=True, help_text='Last time audio was played', null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='total_listening_time_seconds',
            field=models.IntegerField(default=0, help_text='Total seconds of audio listened'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='language',
            field=models.CharField(default='de', help_text='Language code (de, es, etc.)', max_length=10),
        ),
    ]
