# Generated by Django 4.2 on 2026-01-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0008_add_listening_time_tracking'),
    ]

    operations = [
        migrations.AddField(
            model_name='token',
            name='lemma',
            field=models.CharField(blank=True, db_index=True, help_text='Lemmatized form (base form, e.g., sehen for sah/gesehen)', max_length=200, null=True),
        ),
        migrations.AddIndex(
            model_name='token',
            index=models.Index(fields=['lemma'], name='flashcards_t_lemma_idx'),
        ),
    ]
